apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: sanity-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
